### ISSUE TITLE
 scalix-postgres error

### ISSUE THREAD

**Issue by 4it115-Brambory** [scalix/Debian-installer#3]
Hello,
while installing Scalix using this script I have been given this error:
dpkg: error processing package scalix-postgres (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 scalix-postgres
Error while executing "dpkg -i  "/home/scalix/server/scalix-postgres_12.6.0.15981_all.deb""
Do you by any chance know any workaround?

**Comment by pussbb** [comment]
Can you please try scalix 12.7.0 or even scalix 12.7.1 (experimental
postfix support for debian).

I may know where is the problem but issue can be fixed in 12.7.0 or its a
different.

Please try latest one. If you does not know how to get some version please
let me know I will help.
